import {readFile,writeFile,appendFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {createWorld,plan,requestFor,step,simulate,PROFILES,CONFIG,WEEKS} from '../../apps/adaptive-sim/public/engine.js';
const root=new URL('../../',import.meta.url),base=new URL('apps/adaptive-sim/data/',root);const curriculum=JSON.parse(await readFile(new URL('apps/adaptive-sim/public/curriculum.json',root))),nodes=curriculum.nodes;
if(!process.env.TYPESAFE_API_KEY)throw new Error('Missing TYPESAFE_API_KEY');
await mkdir(base,{recursive:true});try{await readFile(new URL('jev-calls.jsonl',base));throw new Error('Existing run; refusing overwrite');}catch(e){if(e.code!=='ENOENT')throw e;}
const sourcePaths=['apps/adaptive-sim/public/engine.js','apps/adaptive-sim/public/questions.js','apps/adaptive-sim/public/curriculum.json','apps/adaptive-sim/data/protocol.json','scripts/adaptive-sim/run.mjs'];
const metadata={startedAt:new Date().toISOString(),gitRevision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),model:'jev-1.13.0',hashes:Object.fromEntries(await Promise.all(sourcePaths.map(async p=>[p,createHash('sha256').update(await readFile(new URL(p,root))).digest('hex')])))};
await writeFile(new URL('run-metadata.json',base),JSON.stringify(metadata,null,2)+'\n');
const world=createWorld(nodes),frames=[],calls=[];
try{while(world.week<WEEKS){const plans=world.pupils.map((_,i)=>plan(world,i)),multi=plans.filter(p=>p.candidates.length>1),choices=plans.map(p=>p.candidates[0].id),decisions=plans.map(p=>({engine:'single',selected:p.candidates[0].id,candidates:p.candidates.map(c=>c.id),reason:'選択肢が1つのため、API判断なし'}));
 if(multi.length){const request=requestFor(multi),t=performance.now();const res=await fetch('https://api.typesafe.ai/v1/systemone',{method:'POST',headers:{Authorization:`Bearer ${process.env.TYPESAFE_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(request),signal:AbortSignal.timeout(45000)});if(!res.ok)throw new Error(`HTTP ${res.status}, week ${world.week+1}`);const response=await res.json(),elapsedMs=performance.now()-t;
 if(response.model!==request.model)throw new Error('Unexpected model');
 for(const [i,p] of multi.entries()){const a=response.answers?.[`next${i}`];if(a?.type!=='choice'||!p.candidates.some(c=>c.id===a.choice))throw new Error('Invalid choice');const probs=a.probabilities;if(!probs||Object.keys(probs).length!==p.candidates.length||p.candidates.some(c=>!Number.isFinite(probs[c.id])||probs[c.id]<0||probs[c.id]>1))throw new Error('Invalid probabilities');const index=plans.findIndex(v=>v.pupilId===p.pupilId);choices[index]=a.choice;decisions[index]={engine:'jev',selected:a.choice,candidates:p.candidates.map(c=>c.id),probabilities:probs,confidence:a.confidence,reason:p.candidates.find(c=>c.id===a.choice).reason,callWeek:world.week+1};}
 const call={week:world.week+1,pupils:multi.map(p=>p.pupilId),request,response,elapsedMs,costUsd:response.usage.input_tokens*.042/1e6};calls.push(call);await appendFile(new URL('jev-calls.jsonl',base),JSON.stringify(call)+'\n');
 }
 const frame=step(world,choices,decisions);frames.push(frame);await appendFile(new URL('jev-frames.jsonl',base),JSON.stringify(frame)+'\n');
 if(world.week%52===0)console.log(`Jev year ${world.week/52}/12, calls ${calls.length}, $${calls.reduce((s,c)=>s+c.costUsd,0).toFixed(4)}`);
}
const runs={jev:frames,rule:simulate(nodes,'rule'),linear:simulate(nodes,'linear')};const summary={...metadata,status:'complete',completedAt:new Date().toISOString(),config:CONFIG,profiles:PROFILES,apiCalls:calls.length,apiQuestions:calls.reduce((s,c)=>s+c.pupils.length,0),costUsd:calls.reduce((s,c)=>s+c.costUsd,0),latencyMedianMs:calls.map(c=>c.elapsedMs).sort((a,b)=>a-b)[Math.floor(calls.length/2)],last:Object.fromEntries(Object.entries(runs).map(([p,f])=>[p,f.at(-1).pupils.map(s=>({id:s.id,passed:s.passed,retained:s.retained,internalRetained:s.internalRetained,returns:s.returns,accuracy:s.accuracy}))]))};
await writeFile(new URL('summary.json',base),JSON.stringify(summary,null,2)+'\n');await writeFile(new URL('apps/adaptive-sim/public/replay.json',root),JSON.stringify({summary,runs})+'\n');console.log(JSON.stringify(summary,null,2));
}catch(e){await writeFile(new URL('failure.json',base),JSON.stringify({message:e.message,completedWeeks:world.week},null,2));throw e;}
